title: "White Pointer Maintenance Manual"
description: "Hardware and maintenance documentation"
remote_theme: just-the-docs/just-the-docs
url: "https://stefsaffern.github.io/uwt-maintenance-manual"

search_enabled: true
