title: White Pointer Maintenance Manual

description: "DSIT Online Maintenance Manual for UWT" 

remote_theme: jekyll/minimal

url: "https://stefsaffern.github.io/uwt-maintenance-manual"

search_enabled: true
